name: Release & Publish Apify on Zapier
on:
    release:
        types: [published]

jobs:
    setup_and_test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version-file: '.nvmrc'

            - name: Install Zapier CLI
              run: npm install -g zapier-platform-cli

            - name: Install dependencies
              run: npm install

            - name: Validate Zapier app
              run: zapier validate --without-style

            - name: Run lint
              run: npm run lint

            - name: Run tests
              run: npm run test
              env:
                  TEST_USER_TOKEN: ${{ secrets.APIFY_TEST_USER_API_TOKEN }}

    update_version_and_changelog:
        runs-on: ubuntu-latest
        needs: setup_and_test
        permissions:
            contents: write
        outputs:
            version: ${{ env.VERSION }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Configure git
              run: |
                  git config --global user.name "Apify Release Bot"
                  git config --global user.email "noreply@apify.com"

            - name: Extract release version
              id: get_version
              run: |
                  FULL_TAG_NAME="${{ github.event.release.tag_name }}"
                  VERSION_NUMBER="${FULL_TAG_NAME#v}"
                  echo "VERSION=${VERSION_NUMBER}" >> $GITHUB_ENV

            - name: Bump package.json version
              run: |
                  echo "Updating package.json version to ${{ env.VERSION }}"
                  npm version ${{ env.VERSION }} --no-git-tag-version

            - name: Update CHANGELOG.md
              run: |
                    if [ -n "${{ github.event.release.body }}" ]; then
                      echo "${RELEASE_BODY}" >> temp_changelog.md
                      echo "" >> temp_changelog.md

                      # Prepend to existing CHANGELOG.md
                      if [ -f CHANGELOG.md ]; then
                        cat CHANGELOG.md >> temp_changelog.md
                      fi

                      # Replace the original CHANGELOG.md with the new one
                      mv temp_changelog.md CHANGELOG.md
                    fi

            - name: Commit changes
              run: |
                  git add package.json package-lock.json CHANGELOG.md
                  if ! git diff --staged --quiet; then
                      TARGET_BRANCH="${{ github.event.release.target_commitish }}"
                      echo "Target branch for push: $TARGET_BRANCH"
                      git commit -m "chore(release): set version to ${{ env.VERSION }}"
                      echo "Pushing changes to $TARGET_BRANCH"
                      git push origin HEAD:"refs/heads/$TARGET_BRANCH"
                  else
                      echo "No changes to commit."
                  fi
              env:
                    GITHUB_TOKEN: ${{ secrets.APIFY_SERVICE_ACCOUNT_GITHUB_TOKEN }}

    publish:
        runs-on: ubuntu-latest
        needs: update_version_and_changelog
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install Zapier CLI
              run: npm install -g zapier-platform-cli

            - name: Create .zapierrc file
              run: |
                  echo '{ "deployKey": "${{ secrets.APIFY_ZAPIER_DEPLOY_KEY }}" }' > ~/.zapierrc

            - name: Push to Zapier
              run: zapier push

            - name: Promote new version
              run: zapier promote ${{ needs.update_version_and_changelog.outputs.version }}
